### ISSUE TITLE
openai.ChatCompletion, but this is no longer supported in openai>=1.0.0

### ISSUE THREAD

**Issue by thomaswhite** [bobbyhiddn/Scrape.md#1]
Traceback (most recent call last):
  File "/home/thomas/.local/bin/scrape_md", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/thomas/.local/share/pipx/venvs/scrape-md/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thomas/.local/share/pipx/venvs/scrape-md/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/thomas/.local/share/pipx/venvs/scrape-md/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thomas/.local/share/pipx/venvs/scrape-md/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thomas/.local/share/pipx/venvs/scrape-md/lib/python3.12/site-packages/scrape/scrape.py", line 78, in main
    filename = to_markdown(title, body)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thomas/.local/share/pipx/venvs/scrape-md/lib/python3.12/site-packages/scrape/scrape.py", line 55, in to_markdown
    formatted_content = send_message(message_log)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thomas/.local/share/pipx/venvs/scrape-md/lib/python3.12/site-packages/scrape/scrape.py", line 12, in send_message
    response = openai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thomas/.local/share/pipx/venvs/scrape-md/lib/python3.12/site-packages/openai/lib/_old_api.py", line 39, in __call__
    raise APIRemovedInV1(symbol=self._symbol)
openai.lib._old_api.APIRemovedInV1: 

You tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. 

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742

**Comment by bobbyhiddn** [comment]
I'll give this a look this weekend and get it updated, I've updated my other AI based apps, so it shouldn't be a big deal.

**Comment by bobbyhiddn** [comment]
Resolved with version 1.0.0, upgraded to new client and improved functionality overall.
